services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env


  web:
    build: .
    command: ./wait.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
