# Generated by Django 5.2.4 on 2025-07-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_customuser_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BmbcChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinderBody', models.CharField(max_length=100)),
                ('pistonTrunnion', models.CharField(max_length=100)),
                ('adjustingTube', models.CharField(max_length=100)),
                ('plungerSpring', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BoggieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogieNo', models.CharField(max_length=100)),
                ('makeYearBuilt', models.CharField(max_length=100)),
                ('incomingDivAndDate', models.CharField(max_length=100)),
                ('deficitComponents', models.CharField(default=None, max_length=100)),
                ('dateOfIOH', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BogieCheckSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogieFrameCondition', models.CharField(max_length=100)),
                ('bolster', models.CharField(max_length=100)),
                ('bolsterSuspensionBracket', models.CharField(max_length=100)),
                ('lowerSpringSeat', models.CharField(max_length=100)),
                ('axleGuide', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WheelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treadDiameterNew', models.CharField(max_length=100)),
                ('lastShopIssueSize', models.CharField(max_length=100)),
                ('condemningDia', models.CharField(max_length=100)),
                ('wheelGauge', models.CharField(max_length=100)),
                ('variationSameAxle', models.CharField(max_length=100)),
                ('variationSameBogie', models.CharField(max_length=100)),
                ('variationSameCoach', models.CharField(max_length=100)),
                ('wheelProfile', models.CharField(max_length=100)),
                ('intermediateWWP', models.CharField(max_length=100)),
                ('bearingSeatDiameter', models.CharField(max_length=100)),
                ('rollerBearingOuterDia', models.CharField(max_length=100)),
                ('rollerBearingBoreDia', models.CharField(max_length=100)),
                ('rollerBearingWidth', models.CharField(max_length=100)),
                ('axleBoxHousingBoreDia', models.CharField(max_length=100)),
                ('wheelDiscWidth', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BogieForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=100, unique=True)),
                ('inspection_by', models.CharField(max_length=100)),
                ('inspectionDate', models.DateField()),
                ('bmbcChecksheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.bmbcchecksheet')),
                ('bogieChecksheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.bogiechecksheet')),
                ('bogieDetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.boggiedetails')),
            ],
        ),
        migrations.CreateModel(
            name='WheelSpecificationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=100, unique=True)),
                ('submitted_by', models.CharField(max_length=100)),
                ('submittedDate', models.DateField()),
                ('fields', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.wheelspecification')),
            ],
        ),
    ]
