# Generated by Django 5.2.4 on 2025-07-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_bmbcchecksheet_boggiedetails_bogiechecksheet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wheelspecificationform',
            old_name='submitted_by',
            new_name='submittedBy',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.AddField(
            model_name='customuser',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
