# Generated by Django 5.2.4 on 2025-07-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_rename_submitted_by_wheelspecificationform_submittedby_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bogieform',
            old_name='inspection_by',
            new_name='inspectionBy',
        ),
    ]
