# Generated by Django 5.2.4 on 2025-07-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_rename_inspection_by_bogieform_inspectionby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boggiedetails',
            old_name='makeYearBuilt',
            new_name='makerYearBuilt',
        ),
    ]
