# Generated by Django 5.2.4 on 2025-07-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_rename_makeyearbuilt_boggiedetails_makeryearbuilt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='file',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
